"""add_composite_tables

Revision ID: 1946d9f1de70
Revises: 741bf11b5126
Create Date: 2026-03-21 02:07:20.131488
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1946d9f1de70'
down_revision: Union[str, None] = '741bf11b5126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_model_artifacts',
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('r2_test', sa.Float(), nullable=True),
    sa.Column('rmse_test', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composite_predictions',
    sa.Column('matrix_polymer', sa.String(length=100), nullable=False),
    sa.Column('filler_formula', sa.String(length=500), nullable=False),
    sa.Column('volume_fraction', sa.Float(), nullable=False),
    sa.Column('connectivity', sa.String(length=50), nullable=False),
    sa.Column('predicted_d33', sa.Float(), nullable=True),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composite_predictions_created_at'), 'composite_predictions', ['created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composite_predictions_created_at'), table_name='composite_predictions')
    op.drop_table('composite_predictions')
    op.drop_table('composite_model_artifacts')
    # ### end Alembic commands ###
