"""add agent_conversations

Revision ID: 96572b8a7617
Revises: 
Create Date: 2026-03-20 01:46:23.408582
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96572b8a7617'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_learning_runs',
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('acquisition_fn', sa.String(length=30), nullable=True),
    sa.Column('total_budget', sa.Integer(), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('found_max_d33_at_iter', sa.Integer(), nullable=True),
    sa.Column('final_max_d33', sa.Float(), nullable=True),
    sa.Column('efficiency_vs_random', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_conversations',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pareto_runs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('n_generations', sa.Integer(), nullable=False),
    sa.Column('population_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbolic_regression_runs',
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('discovered_equations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('best_equation', sa.Text(), nullable=True),
    sa.Column('best_r2', sa.Float(), nullable=True),
    sa.Column('runtime_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('materials',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.Column('d33', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.Column('is_tc_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=True),
    sa.Column('sintering_temp', sa.Float(), nullable=True),
    sa.Column('field_strength', sa.Float(), nullable=True),
    sa.Column('poling_temp', sa.Float(), nullable=True),
    sa.Column('poling_time', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('density_theoretical_pct', sa.Float(), nullable=True),
    sa.Column('planar_coupling', sa.Float(), nullable=True),
    sa.Column('dielectric_const', sa.Float(), nullable=True),
    sa.Column('dielectric_loss', sa.Float(), nullable=True),
    sa.Column('mech_quality_factor', sa.Float(), nullable=True),
    sa.Column('ot_transition', sa.Float(), nullable=True),
    sa.Column('lattice_ratio', sa.Float(), nullable=True),
    sa.Column('max_strain', sa.Float(), nullable=True),
    sa.Column('vickers_hardness', sa.Float(), nullable=True),
    sa.Column('mohs_hardness', sa.Float(), nullable=True),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('matrix_type', sa.String(length=50), nullable=True),
    sa.Column('filler_wt_pct', sa.Float(), nullable=True),
    sa.Column('filler_vol_pct', sa.Float(), nullable=True),
    sa.Column('particle_morphology', sa.String(length=50), nullable=True),
    sa.Column('particle_size_nm', sa.Float(), nullable=True),
    sa.Column('surface_treatment', sa.String(length=100), nullable=True),
    sa.Column('fabrication_method', sa.String(length=100), nullable=True),
    sa.Column('beta_phase_pct', sa.Float(), nullable=True),
    sa.Column('composite_d33', sa.Float(), nullable=True),
    sa.Column('remnant_polarization', sa.Float(), nullable=True),
    sa.Column('coercive_field', sa.Float(), nullable=True),
    sa.Column('reference_doi', sa.String(length=255), nullable=True),
    sa.Column('reference_num', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.SmallInteger(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_imputed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_dataset_id'), 'materials', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_materials_formula'), 'materials', ['formula'], unique=False)
    op.create_index(op.f('ix_materials_is_composite'), 'materials', ['is_composite'], unique=False)
    op.create_table('pareto_solutions',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('formula', sa.String(length=500), nullable=True),
    sa.Column('composition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_d33', sa.Float(), nullable=True),
    sa.Column('predicted_tc', sa.Float(), nullable=True),
    sa.Column('predicted_hardness', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('crowd_distance', sa.Float(), nullable=True),
    sa.Column('use_case', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pareto_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pareto_solutions_run_id'), 'pareto_solutions', ['run_id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('train_d33', sa.Boolean(), nullable=False),
    sa.Column('train_tc', sa.Boolean(), nullable=False),
    sa.Column('train_hardness', sa.Boolean(), nullable=False),
    sa.Column('train_composite', sa.Boolean(), nullable=False),
    sa.Column('best_model_d33', sa.String(length=50), nullable=True),
    sa.Column('best_model_tc', sa.String(length=50), nullable=True),
    sa.Column('r2_d33', sa.Float(), nullable=True),
    sa.Column('r2_tc', sa.Float(), nullable=True),
    sa.Column('rmse_d33', sa.Float(), nullable=True),
    sa.Column('rmse_tc', sa.Float(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atomic_descriptors',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('descriptors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('element_fractions',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('element', sa.String(length=5), nullable=False),
    sa.Column('fraction', sa.Float(), nullable=False),
    sa.Column('site', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_artifacts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('mlflow_artifact', sa.String(length=500), nullable=True),
    sa.Column('r2_train', sa.Float(), nullable=True),
    sa.Column('r2_test', sa.Float(), nullable=True),
    sa.Column('rmse_train', sa.Float(), nullable=True),
    sa.Column('rmse_test', sa.Float(), nullable=True),
    sa.Column('mae_test', sa.Float(), nullable=True),
    sa.Column('cv_r2_mean', sa.Float(), nullable=True),
    sa.Column('cv_r2_std', sa.Float(), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values_path', sa.String(length=500), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_time_sec', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optuna_studies',
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('completed_trials', sa.Integer(), nullable=False),
    sa.Column('best_r2', sa.Float(), nullable=True),
    sa.Column('best_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('all_trials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('param_importances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_logs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_logs_job_id'), 'training_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_training_logs_timestamp'), 'training_logs', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.Column('sintering_temp', sa.Float(), nullable=True),
    sa.Column('composite_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_artifact_id', sa.UUID(), nullable=True),
    sa.Column('predicted_d33', sa.Float(), nullable=True),
    sa.Column('predicted_tc', sa.Float(), nullable=True),
    sa.Column('predicted_hardness', sa.Float(), nullable=True),
    sa.Column('predicted_composite_d33', sa.Float(), nullable=True),
    sa.Column('d33_lower_95', sa.Float(), nullable=True),
    sa.Column('d33_upper_95', sa.Float(), nullable=True),
    sa.Column('tc_lower_95', sa.Float(), nullable=True),
    sa.Column('tc_upper_95', sa.Float(), nullable=True),
    sa.Column('parsed_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_training_logs_timestamp'), table_name='training_logs')
    op.drop_index(op.f('ix_training_logs_job_id'), table_name='training_logs')
    op.drop_table('training_logs')
    op.drop_table('optuna_studies')
    op.drop_table('model_artifacts')
    op.drop_table('element_fractions')
    op.drop_table('atomic_descriptors')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_pareto_solutions_run_id'), table_name='pareto_solutions')
    op.drop_table('pareto_solutions')
    op.drop_index(op.f('ix_materials_is_composite'), table_name='materials')
    op.drop_index(op.f('ix_materials_formula'), table_name='materials')
    op.drop_index(op.f('ix_materials_dataset_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('system_config')
    op.drop_table('symbolic_regression_runs')
    op.drop_table('pareto_runs')
    op.drop_table('datasets')
    op.drop_table('agent_conversations')
    op.drop_table('active_learning_runs')
    # ### end Alembic commands ###
