"""add_alias

Revision ID: 13235545aa3a
Revises: 6bb7ed902131
Create Date: 2026-03-23 14:05:33.357965
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13235545aa3a'
down_revision: Union[str, None] = '6bb7ed902131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_artifacts', sa.Column('alias', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_artifacts', 'alias')
    # ### end Alembic commands ###
