"""Add cascade delete to training jobs

Revision ID: a36f80669ff9
Revises: 9bf0b8ed5362
Create Date: 2026-03-21 03:15:46.686702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36f80669ff9'
down_revision: Union[str, None] = '9bf0b8ed5362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('training_jobs_dataset_id_fkey'), 'training_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'training_jobs', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('training_jobs_dataset_id_fkey'), 'training_jobs', 'datasets', ['dataset_id'], ['id'])
    # ### end Alembic commands ###
