"""initial_schema

Revision ID: c904b3d706d3
Revises: 
Create Date: 2026-05-07 19:43:17.789174
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c904b3d706d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_columns', sa.Integer(), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_composite_fields', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datasets_status', 'datasets', ['status'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.Column('d33', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.Column('vickers_hardness', sa.Float(), nullable=True),
    sa.Column('qm', sa.Float(), nullable=True),
    sa.Column('kp', sa.Float(), nullable=True),
    sa.Column('relative_density_pct', sa.Float(), nullable=True),
    sa.Column('sintering_temp_c', sa.Float(), nullable=True),
    sa.Column('sintering_method', sa.String(length=50), nullable=True),
    sa.Column('ceramic_type', sa.String(length=20), nullable=True),
    sa.Column('fabrication_method', sa.String(length=50), nullable=True),
    sa.Column('matrix_type', sa.String(length=50), nullable=False),
    sa.Column('filler_wt_pct', sa.Float(), nullable=False),
    sa.Column('particle_morphology', sa.String(length=30), nullable=False),
    sa.Column('particle_size_nm', sa.Float(), nullable=True),
    sa.Column('surface_treatment', sa.String(length=30), nullable=False),
    sa.Column('source_doi', sa.String(length=500), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('parse_warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'uid', name='uq_materials_dataset_uid')
    )
    op.create_index('ix_materials_dataset_id', 'materials', ['dataset_id'], unique=False)
    op.create_index('ix_materials_formula', 'materials', ['formula'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('initial_rows', sa.Integer(), nullable=True),
    sa.Column('initial_columns', sa.Integer(), nullable=True),
    sa.Column('final_rows', sa.Integer(), nullable=True),
    sa.Column('final_columns', sa.Integer(), nullable=True),
    sa.Column('artifact_dir', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_jobs_dataset_id', 'training_jobs', ['dataset_id'], unique=False)
    op.create_index('ix_training_jobs_status', 'training_jobs', ['status'], unique=False)
    op.create_table('trained_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('training_job_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=30), nullable=False),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('r2_score', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_version', sa.String(length=10), nullable=False),
    sa.Column('feature_dim', sa.Integer(), nullable=False),
    sa.Column('n_train_samples', sa.Integer(), nullable=False),
    sa.Column('n_test_samples', sa.Integer(), nullable=False),
    sa.Column('supported_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_file_path', sa.String(length=500), nullable=False),
    sa.Column('artifact_dir', sa.String(length=500), nullable=False),
    sa.Column('training_duration_s', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trained_models_dataset_id', 'trained_models', ['dataset_id'], unique=False)
    op.create_index('ix_trained_models_is_default', 'trained_models', ['target', 'is_default'], unique=False)
    op.create_index('ix_trained_models_target', 'trained_models', ['target'], unique=False)
    op.create_table('prediction_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('result_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_batches_model_id', 'prediction_batches', ['model_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('composite_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('d33_predicted', sa.Float(), nullable=True),
    sa.Column('d33_ci_lower', sa.Float(), nullable=True),
    sa.Column('d33_ci_upper', sa.Float(), nullable=True),
    sa.Column('tc_predicted', sa.Float(), nullable=True),
    sa.Column('tc_ci_lower', sa.Float(), nullable=True),
    sa.Column('tc_ci_upper', sa.Float(), nullable=True),
    sa.Column('hardness_predicted', sa.Float(), nullable=True),
    sa.Column('prediction_status', sa.String(length=30), nullable=False),
    sa.Column('prediction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['prediction_batches.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_batch_id', 'predictions', ['batch_id'], unique=False)
    op.create_index('ix_predictions_formula', 'predictions', ['formula'], unique=False)
    op.create_index('ix_predictions_model_id', 'predictions', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_model_id', table_name='predictions')
    op.drop_index('ix_predictions_formula', table_name='predictions')
    op.drop_index('ix_predictions_batch_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_prediction_batches_model_id', table_name='prediction_batches')
    op.drop_table('prediction_batches')
    op.drop_index('ix_trained_models_target', table_name='trained_models')
    op.drop_index('ix_trained_models_is_default', table_name='trained_models')
    op.drop_index('ix_trained_models_dataset_id', table_name='trained_models')
    op.drop_table('trained_models')
    op.drop_index('ix_training_jobs_status', table_name='training_jobs')
    op.drop_index('ix_training_jobs_dataset_id', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index('ix_materials_formula', table_name='materials')
    op.drop_index('ix_materials_dataset_id', table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_datasets_status', table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
